### ISSUE TITLE
Non-default port configuration is not applied

### ISSUE THREAD

**Issue by abirke** [secure-software-engineering/opcua-scanner#5]
As the testing port is statically typed in *ADDR_SUFFIX* in OpcuaUtil.java:26, non-default ports from the configuration file are not considered.

I would suggest to use java.net.InetSocketAddress instead of Inet4Address. It contains an additional port field.

**Comment by mbruns42** [comment]
Good catch, thank you for noticing! Sorry it took us so long to respond, apparently the repo was no longer watched after transferring ownership.
